const countries = [
  { name: 'Afghanistan', iso2: 'AF', iso3: 'AFG', dial_code: '+93' },
  { name: 'Åland Islands', iso2: 'AX', iso3: 'ALA', dial_code: '+358' },
  { name: 'Albania', iso2: 'AL', iso3: 'ALB', dial_code: '+355' },
  { name: 'Algeria', iso2: 'DZ', iso3: 'DZA', dial_code: '+213' },
  { name: 'American Samoa', iso2: 'AS', iso3: 'ASM', dial_code: '+1-684' },
  { name: 'Andorra', iso2: 'AD', iso3: 'AND', dial_code: '+376' },
  { name: 'Angola', iso2: 'AO', iso3: 'AGO', dial_code: '+244' },
  { name: 'Anguilla', iso2: 'AI', iso3: 'AIA', dial_code: '+1-264' },
  { name: 'Antarctica', iso2: 'AQ', iso3: 'ATA', dial_code: '' },
  { name: 'Antigua and Barbuda', iso2: 'AG', iso3: 'ATG', dial_code: '+1-268' },
  { name: 'Argentina', iso2: 'AR', iso3: 'ARG', dial_code: '+54' },
  { name: 'Armenia', iso2: 'AM', iso3: 'ARM', dial_code: '+374' },
  { name: 'Aruba', iso2: 'AW', iso3: 'ABW', dial_code: '+297' },
  { name: 'Australia', iso2: 'AU', iso3: 'AUS', dial_code: '+61' },
  { name: 'Austria', iso2: 'AT', iso3: 'AUT', dial_code: '+43' },
  { name: 'Azerbaijan', iso2: 'AZ', iso3: 'AZE', dial_code: '+994' },
  { name: 'Bahamas', iso2: 'BS', iso3: 'BHS', dial_code: '+1-242' },
  { name: 'Bahrain', iso2: 'BH', iso3: 'BHR', dial_code: '+973' },
  { name: 'Bangladesh', iso2: 'BD', iso3: 'BGD', dial_code: '+880' },
  { name: 'Barbados', iso2: 'BB', iso3: 'BRB', dial_code: '+1-246' },
  { name: 'Belarus', iso2: 'BY', iso3: 'BLR', dial_code: '+375' },
  { name: 'Belgium', iso2: 'BE', iso3: 'BEL', dial_code: '+32' },
  { name: 'Belize', iso2: 'BZ', iso3: 'BLZ', dial_code: '+501' },
  { name: 'Benin', iso2: 'BJ', iso3: 'BEN', dial_code: '+229' },
  { name: 'Bermuda', iso2: 'BM', iso3: 'BMU', dial_code: '+1-441' },
  { name: 'Bhutan', iso2: 'BT', iso3: 'BTN', dial_code: '+975' },
  { name: 'Bolivia', iso2: 'BO', iso3: 'BOL', dial_code: '+591' },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    iso2: 'BQ',
    iso3: 'BES',
    dial_code: '+599',
  },
  {
    name: 'Bosnia and Herzegovina',
    iso2: 'BA',
    iso3: 'BIH',
    dial_code: '+387',
  },
  { name: 'Botswana', iso2: 'BW', iso3: 'BWA', dial_code: '+267' },
  { name: 'Bouvet Island', iso2: 'BV', iso3: 'BVT', dial_code: '' },
  { name: 'Brazil', iso2: 'BR', iso3: 'BRA', dial_code: '+55' },
  {
    name: 'British Indian Ocean Territory',
    iso2: 'IO',
    iso3: 'IOT',
    dial_code: '+246',
  },
  { name: 'Brunei Darussalam', iso2: 'BN', iso3: 'BRN', dial_code: '+673' },
  { name: 'Bulgaria', iso2: 'BG', iso3: 'BGR', dial_code: '+359' },
  { name: 'Burkina Faso', iso2: 'BF', iso3: 'BFA', dial_code: '+226' },
  { name: 'Burundi', iso2: 'BI', iso3: 'BDI', dial_code: '+257' },
  { name: 'Cabo Verde', iso2: 'CV', iso3: 'CPV', dial_code: '+238' },
  { name: 'Cambodia', iso2: 'KH', iso3: 'KHM', dial_code: '+855' },
  { name: 'Cameroon', iso2: 'CM', iso3: 'CMR', dial_code: '+237' },
  { name: 'Canada', iso2: 'CA', iso3: 'CAN', dial_code: '+1' },
  { name: 'Cayman Islands', iso2: 'KY', iso3: 'CYM', dial_code: '+1-345' },
  {
    name: 'Central African Republic',
    iso2: 'CF',
    iso3: 'CAF',
    dial_code: '+236',
  },
  { name: 'Chad', iso2: 'TD', iso3: 'TCD', dial_code: '+235' },
  { name: 'Chile', iso2: 'CL', iso3: 'CHL', dial_code: '+56' },
  { name: 'China', iso2: 'CN', iso3: 'CHN', dial_code: '+86' },
  { name: 'Christmas Island', iso2: 'CX', iso3: 'CXR', dial_code: '+61' },
  {
    name: 'Cocos (Keeling) Islands',
    iso2: 'CC',
    iso3: 'CCK',
    dial_code: '+61',
  },
  { name: 'Colombia', iso2: 'CO', iso3: 'COL', dial_code: '+57' },
  { name: 'Comoros', iso2: 'KM', iso3: 'COM', dial_code: '+269' },
  { name: 'Congo', iso2: 'CG', iso3: 'COG', dial_code: '+242' },
  {
    name: 'Congo, Democratic Republic of the',
    iso2: 'CD',
    iso3: 'COD',
    dial_code: '+243',
  },
  { name: 'Cook Islands', iso2: 'CK', iso3: 'COK', dial_code: '+682' },
  { name: 'Costa Rica', iso2: 'CR', iso3: 'CRI', dial_code: '+506' },
  { name: "Côte d'Ivoire", iso2: 'CI', iso3: 'CIV', dial_code: '+225' },
  { name: 'Croatia', iso2: 'HR', iso3: 'HRV', dial_code: '+385' },
  { name: 'Cuba', iso2: 'CU', iso3: 'CUB', dial_code: '+53' },
  { name: 'Curaçao', iso2: 'CW', iso3: 'CUW', dial_code: '+599' },
  { name: 'Cyprus', iso2: 'CY', iso3: 'CYP', dial_code: '+357' },
  { name: 'Czechia', iso2: 'CZ', iso3: 'CZE', dial_code: '+420' },
  { name: 'Denmark', iso2: 'DK', iso3: 'DNK', dial_code: '+45' },
  { name: 'Djibouti', iso2: 'DJ', iso3: 'DJI', dial_code: '+253' },
  { name: 'Dominica', iso2: 'DM', iso3: 'DMA', dial_code: '+1-767' },
  { name: 'Dominican Republic', iso2: 'DO', iso3: 'DOM', dial_code: '+1-809' },
  { name: 'Ecuador', iso2: 'EC', iso3: 'ECU', dial_code: '+593' },
  { name: 'Egypt', iso2: 'EG', iso3: 'EGY', dial_code: '+20' },
  { name: 'El Salvador', iso2: 'SV', iso3: 'SLV', dial_code: '+503' },
  { name: 'Equatorial Guinea', iso2: 'GQ', iso3: 'GNQ', dial_code: '+240' },
  { name: 'Eritrea', iso2: 'ER', iso3: 'ERI', dial_code: '+291' },
  { name: 'Estonia', iso2: 'EE', iso3: 'EST', dial_code: '+372' },
  { name: 'Eswatini', iso2: 'SZ', iso3: 'SWZ', dial_code: '+268' },
  { name: 'Ethiopia', iso2: 'ET', iso3: 'ETH', dial_code: '+251' },
  {
    name: 'Falkland Islands (Malvinas)',
    iso2: 'FK',
    iso3: 'FLK',
    dial_code: '+500',
  },
  { name: 'Faroe Islands', iso2: 'FO', iso3: 'FRO', dial_code: '+298' },
  { name: 'Fiji', iso2: 'FJ', iso3: 'FJI', dial_code: '+679' },
  { name: 'Finland', iso2: 'FI', iso3: 'FIN', dial_code: '+358' },
  { name: 'France', iso2: 'FR', iso3: 'FRA', dial_code: '+33' },
  { name: 'French Guiana', iso2: 'GF', iso3: 'GUF', dial_code: '+594' },
  { name: 'French Polynesia', iso2: 'PF', iso3: 'PYF', dial_code: '+689' },
  {
    name: 'French Southern Territories',
    iso2: 'TF',
    iso3: 'ATF',
    dial_code: '',
  },
  { name: 'Gabon', iso2: 'GA', iso3: 'GAB', dial_code: '+241' },
  { name: 'Gambia', iso2: 'GM', iso3: 'GMB', dial_code: '+220' },
  { name: 'Georgia', iso2: 'GE', iso3: 'GEO', dial_code: '+995' },
  { name: 'Germany', iso2: 'DE', iso3: 'DEU', dial_code: '+49' },
  { name: 'Ghana', iso2: 'GH', iso3: 'GHA', dial_code: '+233' },
  { name: 'Gibraltar', iso2: 'GI', iso3: 'GIB', dial_code: '+350' },
  { name: 'Greece', iso2: 'GR', iso3: 'GRC', dial_code: '+30' },
  { name: 'Greenland', iso2: 'GL', iso3: 'GRL', dial_code: '+299' },
  { name: 'Grenada', iso2: 'GD', iso3: 'GRD', dial_code: '+1-473' },
  { name: 'Guadeloupe', iso2: 'GP', iso3: 'GLP', dial_code: '+590' },
  { name: 'Guam', iso2: 'GU', iso3: 'GUM', dial_code: '+1-671' },
  { name: 'Guatemala', iso2: 'GT', iso3: 'GTM', dial_code: '+502' },
  { name: 'Guernsey', iso2: 'GG', iso3: 'GGY', dial_code: '+44' },
  { name: 'Guinea', iso2: 'GN', iso3: 'GIN', dial_code: '+224' },
  { name: 'Guinea-Bissau', iso2: 'GW', iso3: 'GNB', dial_code: '+245' },
  { name: 'Guyana', iso2: 'GY', iso3: 'GUY', dial_code: '+592' },
  { name: 'Haiti', iso2: 'HT', iso3: 'HTI', dial_code: '+509' },
  {
    name: 'Heard Island and McDonald Islands',
    iso2: 'HM',
    iso3: 'HMD',
    dial_code: '',
  },
  { name: 'Holy See', iso2: 'VA', iso3: 'VAT', dial_code: '' },
  { name: 'Honduras', iso2: 'HN', iso3: 'HND', dial_code: '+504' },
  { name: 'Hong Kong', iso2: 'HK', iso3: 'HKG', dial_code: '+852' },
  { name: 'Hungary', iso2: 'HU', iso3: 'HUN', dial_code: '+36' },
  { name: 'Iceland', iso2: 'IS', iso3: 'ISL', dial_code: '+354' },
  { name: 'India', iso2: 'IN', iso3: 'IND', dial_code: '+91' },
  { name: 'Indonesia', iso2: 'ID', iso3: 'IDN', dial_code: '+62' },
  {
    name: 'Iran, Islamic Republic of',
    iso2: 'IR',
    iso3: 'IRN',
    dial_code: '+98',
  },
  { name: 'Iraq', iso2: 'IQ', iso3: 'IRQ', dial_code: '+964' },
  { name: 'Ireland', iso2: 'IE', iso3: 'IRL', dial_code: '+353' },
  { name: 'Isle of Man', iso2: 'IM', iso3: 'IMN', dial_code: '+44' },
  { name: 'Israel', iso2: 'IL', iso3: 'ISR', dial_code: '+972' },
  { name: 'Italy', iso2: 'IT', iso3: 'ITA', dial_code: '+39' },
  { name: 'Jamaica', iso2: 'JM', iso3: 'JAM', dial_code: '+1-876' },
  { name: 'Japan', iso2: 'JP', iso3: 'JPN', dial_code: '+81' },
  { name: 'Jersey', iso2: 'JE', iso3: 'JEY', dial_code: '+44' },
  { name: 'Jordan', iso2: 'JO', iso3: 'JOR', dial_code: '+962' },
  { name: 'Kazakhstan', iso2: 'KZ', iso3: 'KAZ', dial_code: '+7' },
  { name: 'Kenya', iso2: 'KE', iso3: 'KEN', dial_code: '+254' },
  { name: 'Kiribati', iso2: 'KI', iso3: 'KIR', dial_code: '+686' },
  {
    name: "Korea, Democratic People's Republic of",
    iso2: 'KP',
    iso3: 'PRK',
    dial_code: '+850',
  },
  { name: 'Korea, Republic of', iso2: 'KR', iso3: 'KOR', dial_code: '+82' },
  { name: 'Kuwait', iso2: 'KW', iso3: 'KWT', dial_code: '+965' },
  { name: 'Kyrgyzstan', iso2: 'KG', iso3: 'KGZ', dial_code: '+996' },
  {
    name: "Lao People's Democratic Republic",
    iso2: 'LA',
    iso3: 'LAO',
    dial_code: '+856',
  },
  { name: 'Latvia', iso2: 'LV', iso3: 'LVA', dial_code: '+371' },
  { name: 'Lebanon', iso2: 'LB', iso3: 'LBN', dial_code: '+961' },
  { name: 'Lesotho', iso2: 'LS', iso3: 'LSO', dial_code: '+266' },
  { name: 'Liberia', iso2: 'LR', iso3: 'LBR', dial_code: '+231' },
  { name: 'Libya', iso2: 'LY', iso3: 'LBY', dial_code: '+218' },
  { name: 'Liechtenstein', iso2: 'LI', iso3: 'LIE', dial_code: '+423' },
  { name: 'Lithuania', iso2: 'LT', iso3: 'LTU', dial_code: '+370' },
  { name: 'Luxembourg', iso2: 'LU', iso3: 'LUX', dial_code: '+352' },
  { name: 'Macao', iso2: 'MO', iso3: 'MAC', dial_code: '+853' },
  { name: 'Madagascar', iso2: 'MG', iso3: 'MDG', dial_code: '+261' },
  { name: 'Malawi', iso2: 'MW', iso3: 'MWI', dial_code: '+265' },
  { name: 'Malaysia', iso2: 'MY', iso3: 'MYS', dial_code: '+60' },
  { name: 'Maldives', iso2: 'MV', iso3: 'MDV', dial_code: '+960' },
  { name: 'Mali', iso2: 'ML', iso3: 'MLI', dial_code: '+223' },
  { name: 'Malta', iso2: 'MT', iso3: 'MLT', dial_code: '+356' },
  { name: 'Marshall Islands', iso2: 'MH', iso3: 'MHL', dial_code: '+692' },
  { name: 'Martinique', iso2: 'MQ', iso3: 'MTQ', dial_code: '+596' },
  { name: 'Mauritania', iso2: 'MR', iso3: 'MRT', dial_code: '+222' },
  { name: 'Mauritius', iso2: 'MU', iso3: 'MUS', dial_code: '+230' },
  { name: 'Mayotte', iso2: 'YT', iso3: 'MYT', dial_code: '+262' },
  { name: 'Mexico', iso2: 'MX', iso3: 'MEX', dial_code: '+52' },
  {
    name: 'Micronesia (Federated States of)',
    iso2: 'FM',
    iso3: 'FSM',
    dial_code: '+691',
  },
  { name: 'Moldova, Republic of', iso2: 'MD', iso3: 'MDA', dial_code: '+373' },
  { name: 'Monaco', iso2: 'MC', iso3: 'MCO', dial_code: '+377' },
  { name: 'Mongolia', iso2: 'MN', iso3: 'MNG', dial_code: '+976' },
  { name: 'Montenegro', iso2: 'ME', iso3: 'MNE', dial_code: '+382' },
  { name: 'Montserrat', iso2: 'MS', iso3: 'MSR', dial_code: '+1-664' },
  { name: 'Morocco', iso2: 'MA', iso3: 'MAR', dial_code: '+212' },
  { name: 'Mozambique', iso2: 'MZ', iso3: 'MOZ', dial_code: '+258' },
  { name: 'Myanmar', iso2: 'MM', iso3: 'MMR', dial_code: '+95' },
  { name: 'Namibia', iso2: 'NA', iso3: 'NAM', dial_code: '+264' },
  { name: 'Nauru', iso2: 'NR', iso3: 'NRU', dial_code: '+674' },
  { name: 'Nepal', iso2: 'NP', iso3: 'NPL', dial_code: '+977' },
  { name: 'Netherlands', iso2: 'NL', iso3: 'NLD', dial_code: '+31' },
  { name: 'New Caledonia', iso2: 'NC', iso3: 'NCL', dial_code: '+687' },
  { name: 'New Zealand', iso2: 'NZ', iso3: 'NZL', dial_code: '+64' },
  { name: 'Nicaragua', iso2: 'NI', iso3: 'NIC', dial_code: '+505' },
  { name: 'Niger', iso2: 'NE', iso3: 'NER', dial_code: '+227' },
  { name: 'Nigeria', iso2: 'NG', iso3: 'NGA', dial_code: '+234' },
  { name: 'Niue', iso2: 'NU', iso3: 'NIU', dial_code: '+683' },
  { name: 'Norfolk Island', iso2: 'NF', iso3: 'NFK', dial_code: '+672' },
  { name: 'North Macedonia', iso2: 'MK', iso3: 'MKD', dial_code: '+389' },
  {
    name: 'Northern Mariana Islands',
    iso2: 'MP',
    iso3: 'MNP',
    dial_code: '+1-670',
  },
  { name: 'Norway', iso2: 'NO', iso3: 'NOR', dial_code: '+47' },
  { name: 'Oman', iso2: 'OM', iso3: 'OMN', dial_code: '+968' },
  { name: 'Pakistan', iso2: 'PK', iso3: 'PAK', dial_code: '+92' },
  { name: 'Palau', iso2: 'PW', iso3: 'PLW', dial_code: '+680' },
  { name: 'Palestine, State of', iso2: 'PS', iso3: 'PSE', dial_code: '+970' },
  { name: 'Panama', iso2: 'PA', iso3: 'PAN', dial_code: '+507' },
  { name: 'Papua New Guinea', iso2: 'PG', iso3: 'PNG', dial_code: '+675' },
  { name: 'Paraguay', iso2: 'PY', iso3: 'PRY', dial_code: '+595' },
  { name: 'Peru', iso2: 'PE', iso3: 'PER', dial_code: '+51' },
  { name: 'Philippines', iso2: 'PH', iso3: 'PHL', dial_code: '+63' },
  { name: 'Pitcairn', iso2: 'PN', iso3: 'PCN', dial_code: '+64' },
  { name: 'Poland', iso2: 'PL', iso3: 'POL', dial_code: '+48' },
  { name: 'Portugal', iso2: 'PT', iso3: 'PRT', dial_code: '+351' },
  { name: 'Puerto Rico', iso2: 'PR', iso3: 'PRI', dial_code: '+1-787' },
  { name: 'Qatar', iso2: 'QA', iso3: 'QAT', dial_code: '+974' },
  { name: 'Réunion', iso2: 'RE', iso3: 'REU', dial_code: '+262' },
  { name: 'Romania', iso2: 'RO', iso3: 'ROU', dial_code: '+40' },
  { name: 'Russian Federation', iso2: 'RU', iso3: 'RUS', dial_code: '+7' },
  { name: 'Rwanda', iso2: 'RW', iso3: 'RWA', dial_code: '+250' },
  { name: 'Saint Barthélemy', iso2: 'BL', iso3: 'BLM', dial_code: '+590' },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    iso2: 'SH',
    iso3: 'SHN',
    dial_code: '+290',
  },
  {
    name: 'Saint Kitts and Nevis',
    iso2: 'KN',
    iso3: 'KNA',
    dial_code: '+1-869',
  },
  { name: 'Saint Lucia', iso2: 'LC', iso3: 'LCA', dial_code: '+1-758' },
  {
    name: 'Saint Martin (French part)',
    iso2: 'MF',
    iso3: 'MAF',
    dial_code: '+590',
  },
  {
    name: 'Saint Pierre and Miquelon',
    iso2: 'PM',
    iso3: 'SPM',
    dial_code: '+508',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    iso2: 'VC',
    iso3: 'VCT',
    dial_code: '+1-784',
  },
  { name: 'Samoa', iso2: 'WS', iso3: 'WSM', dial_code: '+685' },
  { name: 'San Marino', iso2: 'SM', iso3: 'SMR', dial_code: '+378' },
  { name: 'Sao Tome and Principe', iso2: 'ST', iso3: 'STP', dial_code: '+239' },
  { name: 'Saudi Arabia', iso2: 'SA', iso3: 'SAU', dial_code: '+966' },
  { name: 'Senegal', iso2: 'SN', iso3: 'SEN', dial_code: '+221' },
  { name: 'Serbia', iso2: 'RS', iso3: 'SRB', dial_code: '+381' },
  { name: 'Seychelles', iso2: 'SC', iso3: 'SYC', dial_code: '+248' },
  { name: 'Sierra Leone', iso2: 'SL', iso3: 'SLE', dial_code: '+232' },
  { name: 'Singapore', iso2: 'SG', iso3: 'SGP', dial_code: '+65' },
  {
    name: 'Sint Maarten (Dutch part)',
    iso2: 'SX',
    iso3: 'SXM',
    dial_code: '+1-721',
  },
  { name: 'Slovakia', iso2: 'SK', iso3: 'SVK', dial_code: '+421' },
  { name: 'Slovenia', iso2: 'SI', iso3: 'SVN', dial_code: '+386' },
  { name: 'Solomon Islands', iso2: 'SB', iso3: 'SLB', dial_code: '+677' },
  { name: 'Somalia', iso2: 'SO', iso3: 'SOM', dial_code: '+252' },
  { name: 'South Africa', iso2: 'ZA', iso3: 'ZAF', dial_code: '+27' },
  {
    name: 'South Georgia and the South Sandwich Islands',
    iso2: 'GS',
    iso3: 'SGS',
    dial_code: '',
  },
  { name: 'South Sudan', iso2: 'SS', iso3: 'SSD', dial_code: '+211' },
  { name: 'Spain', iso2: 'ES', iso3: 'ESP', dial_code: '+34' },
  { name: 'Sri Lanka', iso2: 'LK', iso3: 'LKA', dial_code: '+94' },
  { name: 'Sudan', iso2: 'SD', iso3: 'SDN', dial_code: '+249' },
  { name: 'Suriname', iso2: 'SR', iso3: 'SUR', dial_code: '+597' },
  { name: 'Svalbard and Jan Mayen', iso2: 'SJ', iso3: 'SJM', dial_code: '+47' },
  { name: 'Sweden', iso2: 'SE', iso3: 'SWE', dial_code: '+46' },
  { name: 'Switzerland', iso2: 'CH', iso3: 'CHE', dial_code: '+41' },
  { name: 'Syrian Arab Republic', iso2: 'SY', iso3: 'SYR', dial_code: '+963' },
  {
    name: 'Taiwan, Province of China',
    iso2: 'TW',
    iso3: 'TWN',
    dial_code: '+886',
  },
  { name: 'Tajikistan', iso2: 'TJ', iso3: 'TJK', dial_code: '+992' },
  {
    name: 'Tanzania, United Republic of',
    iso2: 'TZ',
    iso3: 'TZA',
    dial_code: '+255',
  },
  { name: 'Thailand', iso2: 'TH', iso3: 'THA', dial_code: '+66' },
  { name: 'Timor-Leste', iso2: 'TL', iso3: 'TLS', dial_code: '+670' },
  { name: 'Togo', iso2: 'TG', iso3: 'TGO', dial_code: '+228' },
  { name: 'Tokelau', iso2: 'TK', iso3: 'TKL', dial_code: '+690' },
  { name: 'Tonga', iso2: 'TO', iso3: 'TON', dial_code: '+676' },
  { name: 'Trinidad and Tobago', iso2: 'TT', iso3: 'TTO', dial_code: '+1-868' },
  { name: 'Tunisia', iso2: 'TN', iso3: 'TUN', dial_code: '+216' },
  { name: 'Turkey', iso2: 'TR', iso3: 'TUR', dial_code: '+90' },
  { name: 'Turkmenistan', iso2: 'TM', iso3: 'TKM', dial_code: '+993' },
  {
    name: 'Turks and Caicos Islands',
    iso2: 'TC',
    iso3: 'TCA',
    dial_code: '+1-649',
  },
  { name: 'Tuvalu', iso2: 'TV', iso3: 'TUV', dial_code: '+688' },
  { name: 'Uganda', iso2: 'UG', iso3: 'UGA', dial_code: '+256' },
  { name: 'Ukraine', iso2: 'UA', iso3: 'UKR', dial_code: '+380' },
  { name: 'United Arab Emirates', iso2: 'AE', iso3: 'ARE', dial_code: '+971' },
  {
    name: 'United Kingdom of Great Britain and Northern Ireland',
    iso2: 'GB',
    iso3: 'GBR',
    dial_code: '+44',
  },
  {
    name: 'United States of America',
    iso2: 'US',
    iso3: 'USA',
    dial_code: '+1',
  },
  {
    name: 'United States Minor Outlying Islands',
    iso2: 'UM',
    iso3: 'UMI',
    dial_code: '',
  },
  { name: 'Uruguay', iso2: 'UY', iso3: 'URY', dial_code: '+598' },
  { name: 'Uzbekistan', iso2: 'UZ', iso3: 'UZB', dial_code: '+998' },
  { name: 'Vanuatu', iso2: 'VU', iso3: 'VUT', dial_code: '+678' },
  {
    name: 'Venezuela, Bolivarian Republic of',
    iso2: 'VE',
    iso3: 'VEN',
    dial_code: '+58',
  },
  { name: 'Viet Nam', iso2: 'VN', iso3: 'VNM', dial_code: '+84' },
  {
    name: 'Virgin Islands (British)',
    iso2: 'VG',
    iso3: 'VGB',
    dial_code: '+1-284',
  },
  {
    name: 'Virgin Islands (U.S.)',
    iso2: 'VI',
    iso3: 'VIR',
    dial_code: '+1-340',
  },
  { name: 'Wallis and Futuna', iso2: 'WF', iso3: 'WLF', dial_code: '+681' },
  { name: 'Western Sahara', iso2: 'EH', iso3: 'ESH', dial_code: '+212' },
  { name: 'Yemen', iso2: 'YE', iso3: 'YEM', dial_code: '+967' },
  { name: 'Zambia', iso2: 'ZM', iso3: 'ZMB', dial_code: '+260' },
  { name: 'Zimbabwe', iso2: 'ZW', iso3: 'ZWE', dial_code: '+263' },
];

export default countries;
